import { 
  Customer, 
  Product, 
  Order, 
  Ticket, 
  AiInsight, 
  InventoryMovement, 
  User, 
  Organization,
  AuditLogEntry,
  SystemNotification,
  ModelBenchmarkMetric
} from './types';

export const initialOrganizations: Organization[] = [
  { id: 1, name: 'Apex Dynamics Ltd', slug: 'apex-dynamics', plan: 'Enterprise', status: 'active' },
  { id: 2, name: 'Nova Retail Co', slug: 'nova-retail', plan: 'Pro', status: 'active' },
];

export const demoUsers: User[] = [
  {
    id: 1,
    name: 'Alexander Vance',
    email: 'admin@opsmind.ai',
    role: 'super_admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    current_organization_id: 1,
  },
  {
    id: 2,
    name: 'Elena Rostova',
    email: 'owner@apexdynamics.com',
    role: 'owner',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    current_organization_id: 1,
  },
  {
    id: 3,
    name: 'Marcus Chen',
    email: 'manager@apexdynamics.com',
    role: 'manager',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    current_organization_id: 1,
  },
  {
    id: 4,
    name: 'Sarah Jenkins',
    email: 'staff@apexdynamics.com',
    role: 'staff',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    current_organization_id: 1,
  },
];

export const initialProducts: Product[] = [
  {
    id: 1,
    organization_id: 1,
    category_id: 1,
    supplier_id: 1,
    sku: 'WM-001',
    name: 'Wireless Mouse Pro Ergonomic',
    description: 'Precision dual-mode 2.4GHz and Bluetooth wireless laser mouse with silent click switches.',
    price: 25.00,
    cost: 12.00,
    current_stock: 18,
    reorder_level: 20,
    safety_stock: 15,
    status: 'low_stock',
    category: { id: 1, name: 'Electronics & Peripherals' },
    supplier: { id: 1, name: 'Pacific Hardware Corp', lead_time_days: 7 },
  },
  {
    id: 2,
    organization_id: 1,
    category_id: 1,
    supplier_id: 1,
    sku: 'KB-102',
    name: 'Mechanical Tactile Keyboard',
    description: 'Compact 75% hot-swappable mechanical keyboard with RGB backlighting.',
    price: 40.00,
    cost: 19.50,
    current_stock: 42,
    reorder_level: 15,
    safety_stock: 20,
    status: 'in_stock',
    category: { id: 1, name: 'Electronics & Peripherals' },
    supplier: { id: 1, name: 'Pacific Hardware Corp', lead_time_days: 5 },
  },
  {
    id: 3,
    organization_id: 1,
    category_id: 2,
    supplier_id: 2,
    sku: 'HS-300',
    name: 'Active Noise-Cancelling Headset',
    description: 'Studio-grade over-ear wireless headset with 40-hour battery life.',
    price: 89.00,
    cost: 42.00,
    current_stock: 8,
    reorder_level: 10,
    safety_stock: 10,
    status: 'low_stock',
    category: { id: 2, name: 'Audio & Accessories' },
    supplier: { id: 2, name: 'Sonic Sound Distro', lead_time_days: 8 },
  },
  {
    id: 4,
    organization_id: 1,
    category_id: 3,
    supplier_id: 1,
    sku: 'MN-404',
    name: 'UltraWide 34" 4K Monitor',
    description: 'IPS curved display with 144Hz refresh rate and USB-C 90W power delivery.',
    price: 450.00,
    cost: 280.00,
    current_stock: 14,
    reorder_level: 5,
    safety_stock: 8,
    status: 'in_stock',
    category: { id: 3, name: 'Office Workstations' },
    supplier: { id: 1, name: 'Pacific Hardware Corp', lead_time_days: 10 },
  },
];

// Seeded Customers including Sarah Williams (Section 12) & John Miller (Section 15)
export const initialCustomers: Customer[] = [
  {
    id: 1,
    organization_id: 1,
    name: 'Sarah Williams',
    email: 'sarah.williams@apexenterprise.com',
    phone: '+1 (555) 438-9021',
    company: 'Apex Enterprise Solutions',
    status: 'active',
    health_score: 86,
    health_factors: {
      recency: 85,
      purchase_frequency: 90,
      revenue: 92,
      support: 65,
      engagement: 80,
      refunds: 95,
    },
    lifetime_value: 4820.00,
    total_orders: 18,
    last_order_at: '2026-08-28T10:15:00Z',
    latest_ai_score: {
      customer_id: 1,
      churn_risk_score: 0.08,
      risk_level: 'LOW',
      key_drivers: [
        '18 lifetime orders with high monetary spend ($4,820)',
        'Purchased within last 7 days',
        'Support ticket #2048 promptly resolved with satisfaction'
      ],
      suggested_action: 'Enroll in VIP priority advisory group and target with new hardware preview.',
      calculated_at: '2026-09-04T08:00:00Z',
    },
    timeline: [
      { time: 'Today 10:15 AM', title: 'Purchased $240', desc: 'Hardware accessories batch (Order #ORD-5082)', icon: 'shopping-cart', color: 'emerald' },
      { time: 'Today 11:30 AM', title: 'Opened support ticket', desc: 'Ticket #2048: Charge inquiry automatically classified as Billing', icon: 'life-buoy', color: 'indigo' },
      { time: 'Today 01:15 PM', title: 'Ticket resolved', desc: 'Duplicate charge verified and credited back by Billing Team', icon: 'check-circle', color: 'emerald' },
      { time: 'Today 02:45 PM', title: 'Received email', desc: 'Dispatched satisfaction survey & VIP loyalty rebate', icon: 'mail', color: 'purple' },
      { time: 'Today 03:00 PM', title: 'AI health score updated', desc: 'Customer health recalculated to 86% 🟢 HEALTHY', icon: 'sparkles', color: 'emerald' },
    ],
  },
  {
    id: 2,
    organization_id: 1,
    name: 'John Miller',
    email: 'john.miller@orbitalsystems.io',
    phone: '+1 (555) 892-3311',
    company: 'Orbital Systems Inc',
    status: 'at_risk',
    health_score: 32,
    health_factors: {
      recency: 25,
      purchase_frequency: 30,
      revenue: 70,
      support: 20,
      engagement: 15,
      refunds: 40,
    },
    lifetime_value: 310.00,
    total_orders: 2,
    last_order_at: '2026-07-01T14:20:00Z',
    latest_ai_score: {
      customer_id: 2,
      churn_risk_score: 0.82,
      risk_level: 'CRITICAL',
      key_drivers: [
        '65 days since last purchase transaction',
        'Low lifetime order frequency (2 orders)',
        'Support frustration and negative delivery sentiment'
      ],
      suggested_action: 'Trigger high-priority outbound call by Marcus Chen with a 25% courtesy re-engagement code.',
      calculated_at: '2026-09-04T08:00:00Z',
    },
    timeline: [
      { time: '65 days ago', title: 'Placed second order', desc: 'Ordered basic mouse ($45)', icon: 'shopping-cart', color: 'slate' },
      { time: '40 days ago', title: 'Filed complaint ticket', desc: 'Unresolved delivery dispute', icon: 'alert-triangle', color: 'rose' },
      { time: 'Today', title: 'AI Churn Escalation', desc: 'Health score collapsed to 32% 🔴 AT RISK', icon: 'alert-circle', color: 'rose' },
    ],
  },
  {
    id: 3,
    organization_id: 1,
    name: 'David Sterling',
    email: 'david.sterling@acmecorp.com',
    phone: '+1 (555) 742-9911',
    company: 'Acme Corporation',
    status: 'active',
    health_score: 88,
    health_factors: {
      recency: 90,
      purchase_frequency: 85,
      revenue: 80,
      support: 95,
      engagement: 85,
      refunds: 100,
    },
    lifetime_value: 1840.00,
    total_orders: 6,
    last_order_at: '2026-09-01T14:30:00Z',
    latest_ai_score: {
      customer_id: 3,
      churn_risk_score: 0.12,
      risk_level: 'LOW',
      key_drivers: [
        'Recent order placed 3 days ago',
        'Frequent 6-order lifetime track record',
        'Zero open support tickets'
      ],
      suggested_action: 'Enroll in VIP loyalty tier; eligible for annual volume contract discount.',
      calculated_at: '2026-09-04T08:00:00Z',
    },
  },
];

export const initialMovements: InventoryMovement[] = [
  {
    id: 101,
    organization_id: 1,
    product_id: 1,
    product: { name: 'Wireless Mouse Pro Ergonomic', sku: 'WM-001' },
    type: 'PURCHASE',
    quantity: 25,
    balance_after: 25,
    reference_type: 'PO',
    reference_id: 'PO-8821',
    notes: 'Bulk inbound restock shipment received from Pacific Hardware Corp',
    created_at: '2026-08-28T10:00:00Z',
  },
  {
    id: 102,
    organization_id: 1,
    product_id: 1,
    product: { name: 'Wireless Mouse Pro Ergonomic', sku: 'WM-001' },
    type: 'SALE',
    quantity: -5,
    balance_after: 20,
    reference_type: 'Order',
    reference_id: 'ORD-501',
    notes: 'Customer Order #501 fulfillment dispatch',
    created_at: '2026-09-01T15:20:00Z',
  },
  {
    id: 103,
    organization_id: 1,
    product_id: 1,
    product: { name: 'Wireless Mouse Pro Ergonomic', sku: 'WM-001' },
    type: 'SALE',
    quantity: -2,
    balance_after: 18,
    reference_type: 'Order',
    reference_id: 'ORD-5001',
    notes: 'Customer Order #5001 fulfillment dispatch (triggers LOW STOCK warning)',
    created_at: '2026-09-03T16:45:00Z',
  },
];

export const initialOrders: Order[] = [
  {
    id: 5082,
    organization_id: 1,
    customer_id: 1,
    customer: initialCustomers[0],
    order_number: 'ORD-5082',
    status: 'completed',
    subtotal: 218.00,
    tax_amount: 22.00,
    discount_amount: 0.00,
    total_amount: 240.00,
    payment_status: 'paid',
    notes: 'Sarah Williams hardware peripherals order ($240)',
    items: [
      { product_id: 1, product: initialProducts[0], quantity: 4, unit_price: 25.00, subtotal: 100.00 },
      { product_id: 2, product: initialProducts[1], quantity: 2, unit_price: 40.00, subtotal: 80.00 },
    ],
    payments: [
      { id: 1, order_id: 5082, transaction_reference: 'TXN-508291', amount: 240.00, payment_method: 'credit_card', status: 'successful', created_at: '2026-08-28T10:15:00Z' }
    ],
    created_at: '2026-08-28T10:15:00Z',
  },
  {
    id: 5001,
    organization_id: 1,
    customer_id: 3,
    customer: initialCustomers[2],
    order_number: 'ORD-5001',
    status: 'completed',
    subtotal: 90.00,
    tax_amount: 9.00,
    discount_amount: 0.00,
    total_amount: 99.00,
    payment_status: 'paid',
    notes: 'Wireless Mouse x 2 ($50) + Keyboard x 1 ($40) + Tax $9 = $99',
    items: [
      { product_id: 1, product: initialProducts[0], quantity: 2, unit_price: 25.00, subtotal: 50.00 },
      { product_id: 2, product: initialProducts[1], quantity: 1, unit_price: 40.00, subtotal: 40.00 },
    ],
    payments: [
      { id: 2, order_id: 5001, transaction_reference: 'TXN-994821', amount: 99.00, payment_method: 'credit_card', status: 'successful', created_at: '2026-09-03T16:45:00Z' }
    ],
    created_at: '2026-09-03T16:45:00Z',
  },
];

// Seeded Tickets: Including Ticket #2048 (Section 13 & 14)
export const initialTickets: Ticket[] = [
  {
    id: 2048,
    organization_id: 1,
    customer_id: 1,
    customer: initialCustomers[0],
    assigned_team: 'Billing & Payments Team',
    ticket_number: 'TCK-2048',
    subject: 'I was charged twice for my order.',
    status: 'resolved',
    priority: 'high',
    sentiment: 'negative',
    ai_confidence: 0.94,
    category: 'Billing',
    messages: [
      {
        id: 1,
        ticket_id: 2048,
        sender_type: 'customer',
        sender_name: 'Sarah Williams',
        message: 'I was charged twice for my order #ORD-5082 ($240.00). Please review the duplicate transaction and issue a credit refund immediately.',
        created_at: '2026-09-04T11:30:00Z',
      },
      {
        id: 2,
        ticket_id: 2048,
        sender_type: 'staff',
        sender_name: 'Sarah Jenkins',
        message: 'Hello Sarah, our billing team has confirmed the duplicate charge and issued an immediate $240 reversal back to your credit card.',
        created_at: '2026-09-04T13:15:00Z',
      },
    ],
    created_at: '2026-09-04T11:30:00Z',
  },
  {
    id: 2041,
    organization_id: 1,
    customer_id: 2,
    customer: initialCustomers[1],
    assigned_team: 'Technical Support Team',
    ticket_number: 'TCK-2041',
    subject: 'Firmware pairing issue with Bluetooth receiver',
    status: 'open',
    priority: 'high',
    sentiment: 'negative',
    ai_confidence: 0.89,
    category: 'Technical Support',
    messages: [
      {
        id: 3,
        ticket_id: 2041,
        sender_type: 'customer',
        sender_name: 'John Miller',
        message: 'The Bluetooth receiver drops connection every 10 minutes on Windows 11. I am waiting for an urgent replacement.',
        created_at: '2026-09-03T11:20:00Z',
      },
    ],
    created_at: '2026-09-03T11:20:00Z',
  },
];

// Seeded AI Business Insights (Section 19)
export const initialInsights: AiInsight[] = [
  {
    id: 'INS-REV-001',
    category: 'REVENUE',
    title: 'Revenue Acceleration Pattern',
    description: '📈 Revenue increased 18% this month driven by strong corporate workstation expansions.',
    severity: 'OPPORTUNITY',
    impact_metric: '+18% MoM Growth',
    recommended_action: 'Increase supplier replenishment buffers for top 20% high-margin products to capture sustained demand.',
    status: 'active',
    confidence_score: 0.95,
  },
  {
    id: 'INS-INV-002',
    category: 'INVENTORY',
    title: 'Critical Stock Depletion Horizon',
    description: '⚠️ 12 products are expected to reach critical stock levels within 14 days based on current sales velocity.',
    severity: 'CRITICAL',
    impact_metric: '12 SKUs At Risk',
    recommended_action: 'Draft automated purchase orders to primary suppliers with lead time buffer.',
    status: 'active',
    confidence_score: 0.94,
  },
  {
    id: 'INS-CRM-003',
    category: 'CUSTOMER_RETENTION',
    title: 'Elevated High-Value Churn Exposure',
    description: '🔴 8 high-value customers have elevated churn probability due to support friction or extended purchase dormancy.',
    severity: 'CRITICAL',
    impact_metric: '8 High-LTV Accounts',
    recommended_action: 'Launch VIP proactive customer success outreach sequence and apply loyalty credits.',
    status: 'active',
    confidence_score: 0.91,
  },
  {
    id: 'INS-HLP-004',
    category: 'HELPDESK',
    title: 'Billing Ticket Surge Detected',
    description: '🎫 Billing tickets increased 27% this week following the merchant gateway migration.',
    severity: 'WARNING',
    impact_metric: '+27% Billing Inquiries',
    recommended_action: 'Audit stripe webhook retries and auto-route to Billing & Payments Team.',
    status: 'active',
    confidence_score: 0.92,
  },
  {
    id: 'INS-BKT-005',
    category: 'REVENUE',
    title: 'Market Basket Association Rule',
    description: '💡 Customers who purchase keyboards have a high probability of purchasing a mouse within 30 days (84% association lift).',
    severity: 'OPPORTUNITY',
    impact_metric: '84% Association Lift',
    recommended_action: 'Activate 10% Workstation Bundle promotional package in the POS checkout studio.',
    status: 'active',
    confidence_score: 0.93,
  },
];

// Seeded Audit Logs (Section 29)
export const initialAuditLogs: AuditLogEntry[] = [
  {
    id: 1,
    organization_id: 1,
    user_name: 'John',
    action: 'price_change',
    entity_type: 'Product',
    entity_id: 'WM-001',
    summary: 'Admin changed product price: Wireless Mouse ($50.00 -> $45.00)',
    old_values: { price: 50.00 },
    new_values: { price: 45.00 },
    ip_address: '192.168.1.104',
    created_at: '2026-09-04T09:30:00Z',
  },
  {
    id: 2,
    organization_id: 1,
    user_name: 'Marcus Chen',
    action: 'inventory_adjust',
    entity_type: 'Product',
    entity_id: 'KB-102',
    summary: 'Inventory adjusted: Mechanical Tactile Keyboard (+20 units received)',
    old_values: { stock: 22 },
    new_values: { stock: 42 },
    ip_address: '192.168.1.115',
    created_at: '2026-09-04T09:45:00Z',
  },
  {
    id: 3,
    organization_id: 1,
    user_name: 'Elena Rostova',
    action: 'role_change',
    entity_type: 'User',
    entity_id: 'USR-3',
    summary: 'Permission changed: Marcus Chen assigned Operations Manager role',
    old_values: { role: 'staff' },
    new_values: { role: 'manager' },
    ip_address: '192.168.1.100',
    created_at: '2026-09-03T16:20:00Z',
  },
  {
    id: 4,
    organization_id: 1,
    user_name: 'Sarah Jenkins',
    action: 'order_create',
    entity_type: 'Order',
    entity_id: 'ORD-5082',
    summary: 'Atomic order created for Sarah Williams: $240.00 via Credit Card',
    old_values: {},
    new_values: { total: 240.00, status: 'completed' },
    ip_address: '192.168.1.120',
    created_at: '2026-08-28T10:15:00Z',
  },
];

// Seeded System Notifications (Section 24)
export const initialNotifications: SystemNotification[] = [
  {
    id: 1,
    organization_id: 1,
    type: 'inventory_alert',
    severity: 'warning',
    title: '⚠️ Inventory Alert: Wireless Mouse',
    message: 'Current Stock: 12, Predicted Demand: 72, Recommended Order: 80 units.',
    data: { sku: 'WM-001', current: 12, predicted: 72, recommended: 80 },
    read_at: null,
    created_at: '2026-09-04T08:00:00Z',
  },
  {
    id: 2,
    organization_id: 1,
    type: 'billing_surge',
    severity: 'warning',
    title: '🎫 Billing Inquiry Influx',
    message: 'Duplicate billing charge tickets increased 27% this week.',
    data: { growth_pct: 27 },
    read_at: null,
    created_at: '2026-09-04T08:30:00Z',
  },
  {
    id: 3,
    organization_id: 1,
    type: 'churn_warning',
    severity: 'critical',
    title: '🔴 High Churn Risk: John Miller',
    message: 'Customer health score dropped to 32% (At Risk). Immediate manager outreach recommended.',
    data: { customer: 'John Miller', health: 32 },
    read_at: null,
    created_at: '2026-09-04T09:00:00Z',
  },
];

// Model Benchmark Evaluation Data (Section 17)
export const initialModelBenchmarks: ModelBenchmarkMetric[] = [
  {
    model_name: 'Linear Trend / ARIMA (Intermediate)',
    mae: 1.05,
    rmse: 1.35,
    mape: 3.26,
    projected_30d_demand: 87,
    is_best_fit: true,
  },
  {
    model_name: 'Moving Average (Baseline)',
    mae: 4.19,
    rmse: 4.47,
    mape: 13.15,
    projected_30d_demand: 76,
    is_best_fit: false,
  },
  {
    model_name: 'Exponential Smoothing / Random Forest (Advanced)',
    mae: 4.79,
    rmse: 5.05,
    mape: 15.03,
    projected_30d_demand: 92,
    is_best_fit: false,
  },
];
